plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.9.22'
    id 'org.jetbrains.kotlin.plugin.serialization' version '1.9.22'
    id 'application'
}
repositories { mavenCentral() }
dependencies {
    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3'
}
application {
    mainClass = 'JsonTestKt'
}
